### ISSUE TITLE
Video Display

### ISSUE THREAD

**Issue by michelle-easter** [MindMakersProject/website-BE#2]
We need to have a carousel (or some other implementation) for allowing viewing of multiple videos under the video tab. 

The video that is currently up should have the title: "Mind Makers: Making Mindful Matters Matter"

Also, this one (https://vimeo.com/163459355) needs to be added, with the title: "Mind Makers: Workshop Tips for Max Impact"

@wcjohnson11

**Comment by wcjohnson11** [comment]
resolved
