### ISSUE TITLE
Update Team Section of Website

### ISSUE THREAD

**Issue by michelle-easter** [MindMakersProject/website-BE#3]
- [ ] Add Allison to the website. She should come before Carla in the Volunteer Coordinator section.

Her Bio Should read:

Allison Ayad. Liaison. 
Allison is an undergraduate student pursuing a degree in Mechanical Engineering. She has been engaged in STEM since the age of nine, building competitive robots and participating in programs which promote teamwork in building robots to solve a variety of challenges. Through the mentorship she has received, she has developed confidence in her ability to pursue a career in STEM and aspires to work on robotic systems for the exploration of space or disaster mitigation. She is excited to be a part of Mind Makers because she believes exposure to engineering can instill a new passion in people’s lives.

Her photo is here:
![allisonayad200x200](https://cloud.githubusercontent.com/assets/15645850/19506674/6f272c38-9582-11e6-8ce6-be00dd093a97.jpg)
- [ ] Change Erika's title to "Hardware Engineer"

**Comment by wcjohnson11** [comment]
@michelle-easter I added Allison and updated Erika's title. What section should I add myself under?
